AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: OncoGenie - Cancer Risk Analysis API

Parameters:
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-5-sonnet-20240620-v1:0

Resources:
  # ── IAM Role (Least Privilege) ──────────────────────────────────────────────
  OncoGenieFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: OncoGenieLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: OncoGenieBedrockInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Principle of Least Privilege: Only InvokeModel on specific model
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource:
                  - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0
                  - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-text-express-v1

  # ── Lambda Function ──────────────────────────────────────────────────────────
  OncoGenieFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: oncogenie-analysis
      Handler: index.handler
      Runtime: python3.12
      CodeUri: src/
      Role: !GetAtt OncoGenieFunctionRole.Arn
      Timeout: 90           # Scraping + inference can take 30-60s
      MemorySize: 512
      Environment:
        Variables:
          BEDROCK_MODEL_ID: !Ref BedrockModelId
      Events:
        AnalyzeApi:
          Type: Api
          Properties:
            Path: /analyze
            Method: post
            RestApiId: !Ref OncoGenieApi
        OptionsApi:
          Type: Api
          Properties:
            Path: /analyze
            Method: options
            RestApiId: !Ref OncoGenieApi

  # ── API Gateway ──────────────────────────────────────────────────────────────
  OncoGenieApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: oncogenie-api
      StageName: prod
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${OncoGenieApi}.execute-api.${AWS::Region}.amazonaws.com/prod/analyze
    Export:
      Name: OncoGenieApiEndpoint
